on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
name: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg

      - run: cargo build
      - run: cargo test
      - run: cargo fmt --check
